[project]
name = "micropython-scheduler"
version = "1.0.0"
description = "Cooperative scheduler module for MicroPython."
license = "SUL-1.0"
license-files = [ "LICENSE.md" ]
authors = [
    { name = "S. R. Lincoln", email = "oss@codeability.co.uk" },
]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: MicroPython",
]
dependencies = []

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["scheduler*"]


# --- Pytest ---
[tool.pytest.ini_options]
minversion = "6.0"
pythonpath = ["scheduler"]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "*_tests.py"]
